### ISSUE TITLE
Server slot count

### ISSUE THREAD

**Issue by rwalkos** [Trojaner25/SaveLoad#2]
Seems to me this plugin is only allowing 7 people to connect. When more try to join it kills them and boots them Kind of a troll plugin at the moment. Is there a fix for this?

**Comment by Trojaner25** [comment]
This is not the case.
The plugin does not limit player count.

**Comment by rwalkos** [comment]
Thank you. I just tested to see if it was this plugin causing the issue and I don't think it was. Looking for another cause. Thank you for the fast response. I actually came here to delete my comment.
